### ISSUE TITLE
Make configuration compatible with kubernetes provider

### ISSUE THREAD

**Issue by TMaYaD** [mingfang/terraform-provider-k8s#3]
The provider configuration currently depends upon kubeconfig file which is not always desirable. 
Make provider configurable using parameters directly following official kubernetes provider example.

**Comment by mingfang** [comment]
@TMaYaD Thanks for creating this issue.  Unfortunately due to the nature of how this plugin works, the configuration can not be done the same way.

This plugin dynamically discover the available resources by getting the open-api information from the api-server.  This step requires the credentials and information from the kubeconfig file.  

The advantage of dynamic discovery is this plugin supports all Kubernetes resources and automatically support new resources introduced by Kubernetes upgrades or by the user using Custom Resource Definitions(CRDs).

The discovery process happens very early in the plugins initialization process here https://github.com/mingfang/terraform-provider-k8s/blob/e2aabe096f5918ee2bb68e695f3952185f2407c7/k8s/provider.go#L18  

In fact, the plugin configuration process happens after this in a callback here https://github.com/mingfang/terraform-provider-k8s/blob/e2aabe096f5918ee2bb68e695f3952185f2407c7/k8s/provider.go#L26

Because of this sequence of events, this plugin can not be configured the same way as the official Kubernetes plugin.  They may change how plugins are initialized in the future version of the Terraform SDK after the 0.12 release.  Until then, I'm closing this issue for now.  Thanks again for your contribution.
